# Generated by Django 3.0.7 on 2020-07-08 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('the_year_of_publishment', models.DateTimeField(blank=True, null=True)),
                ('cover', models.ImageField(upload_to='')),
                ('ean', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('kat_nr', models.CharField(blank=True, max_length=100, null=True)),
                ('country_of_issued_of_album', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.CharField(choices=[(4, '★★★★'), (2, '★★'), (1, '★'), (5, '★★★★★'), (3, '★★★')], default=5, max_length=10)),
            ],
            options={
                'verbose_name': 'album',
                'ordering': ['-the_year_of_publishment'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('album', models.ManyToManyField(to='musiccollection.Album')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MusicLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_label', models.ManyToManyField(to='musiccollection.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country_of_origin', models.CharField(blank=True, max_length=200, null=True)),
                ('foundation_year', models.DateTimeField()),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('album', models.ManyToManyField(to='musiccollection.Album')),
                ('genre', models.ManyToManyField(to='musiccollection.Genre')),
            ],
            options={
                'unique_together': {('name', 'country_of_origin')},
            },
        ),
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='musiccollection.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(to='musiccollection.Genre'),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('title', 'band')},
        ),
    ]
