# Generated by Django 3.0.7 on 2020-07-08 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musiccollection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='bio',
        ),
        migrations.AlterField(
            model_name='album',
            name='band',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='musiccollection.Artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='album/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.CharField(choices=[(2, '★★'), (4, '★★★★'), (5, '★★★★★'), (1, '★'), (3, '★★★')], default=5, max_length=10),
        ),
        migrations.AlterField(
            model_name='artist',
            name='album',
            field=models.ManyToManyField(blank=True, to='musiccollection.Album'),
        ),
    ]
