# Generated by Django 3.0.7 on 2020-07-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiccollection', '0002_auto_20200708_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.CharField(choices=[(3, '★★★'), (1, '★'), (4, '★★★★'), (2, '★★'), (5, '★★★★★')], default=5, max_length=10),
        ),
    ]
