# Generated by Django 3.0.7 on 2020-07-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiccollection', '0003_auto_20200708_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='album/covers'),
        ),
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.CharField(choices=[(5, '★★★★★'), (3, '★★★'), (1, '★'), (2, '★★'), (4, '★★★★')], default=5, max_length=10),
        ),
    ]
